/*
 * MoiKiitos API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.52
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from './ApiClient';
import {AccountLoginDto} from './model/AccountLoginDto';
import {AccountRegistrationDto} from './model/AccountRegistrationDto';
import {FeedQueryDto} from './model/FeedQueryDto';
import {PageResultUser} from './model/PageResultUser';
import {Post} from './model/Post';
import {PostCreateDto} from './model/PostCreateDto';
import {ResponseBodyEmitter} from './model/ResponseBodyEmitter';
import {User} from './model/User';
import {UserFollowQueryDto} from './model/UserFollowQueryDto';
import {UserQueryDto} from './model/UserQueryDto';
import {AccountApi} from './api/AccountApi';
import {PostApi} from './api/PostApi';
import {UserApi} from './api/UserApi';

/**
* Object.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var MoiKiitosApi = require('index'); // See note below*.
* var xxxSvc = new MoiKiitosApi.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new MoiKiitosApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new MoiKiitosApi.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new MoiKiitosApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version v1
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The AccountLoginDto model constructor.
     * @property {module:model/AccountLoginDto}
     */
    AccountLoginDto,

    /**
     * The AccountRegistrationDto model constructor.
     * @property {module:model/AccountRegistrationDto}
     */
    AccountRegistrationDto,

    /**
     * The FeedQueryDto model constructor.
     * @property {module:model/FeedQueryDto}
     */
    FeedQueryDto,

    /**
     * The PageResultUser model constructor.
     * @property {module:model/PageResultUser}
     */
    PageResultUser,

    /**
     * The Post model constructor.
     * @property {module:model/Post}
     */
    Post,

    /**
     * The PostCreateDto model constructor.
     * @property {module:model/PostCreateDto}
     */
    PostCreateDto,

    /**
     * The ResponseBodyEmitter model constructor.
     * @property {module:model/ResponseBodyEmitter}
     */
    ResponseBodyEmitter,

    /**
     * The User model constructor.
     * @property {module:model/User}
     */
    User,

    /**
     * The UserFollowQueryDto model constructor.
     * @property {module:model/UserFollowQueryDto}
     */
    UserFollowQueryDto,

    /**
     * The UserQueryDto model constructor.
     * @property {module:model/UserQueryDto}
     */
    UserQueryDto,

    /**
    * The AccountApi service constructor.
    * @property {module:api/AccountApi}
    */
    AccountApi,

    /**
    * The PostApi service constructor.
    * @property {module:api/PostApi}
    */
    PostApi,

    /**
    * The UserApi service constructor.
    * @property {module:api/UserApi}
    */
    UserApi
};
