server.port: 8080

spring:
  application.name: MoiKiitos
  #  profiles.active: local

  flyway:
    enabled: true
  cache:
    type: redis
    redis:
      time-to-live: 600000 # 10 mins
      cache-null-values: true
  # redis
  data:
    redis:
      host: localhost
      port: 63797
      # password:
      database: 0

logging:
  level:
    com.example.moikiitos.repository.mybatis.mapper: DEBUG
mybatis:
  configuration:
    map-underscore-to-camel-case: true


# swagger configuration
# please visit http://localhost:8080/swagger-ui/
springdoc.api-docs.path: /api-docs
springdoc.api-docs.enabled: true
springdoc.swagger-ui.path: /swagger-ui
springdoc.swagger-ui.enabled: true
springdoc.show-actuator: false

permitAllUrls: /account/login,
  /account/registration,
  /error,
  /api-docs, /api-docs/*, /swagger-ui, /swagger-ui/*,
  /actuator/*
