/*
 * MoiKiitos API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.52
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The AccountLoginDto model module.
 * @module model/AccountLoginDto
 * @version v1
 */
export class AccountLoginDto {
  /**
   * Constructs a new <code>AccountLoginDto</code>.
   * @alias module:model/AccountLoginDto
   * @class
   * @param nameOrEmail {String} 
   * @param password {Array.<String>} 
   */
  constructor(nameOrEmail, password) {
    this.nameOrEmail = nameOrEmail;
    this.password = password;
  }

  /**
   * Constructs a <code>AccountLoginDto</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/AccountLoginDto} obj Optional instance to populate.
   * @return {module:model/AccountLoginDto} The populated <code>AccountLoginDto</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new AccountLoginDto();
      if (data.hasOwnProperty('nameOrEmail'))
        obj.nameOrEmail = ApiClient.convertToType(data['nameOrEmail'], 'String');
      if (data.hasOwnProperty('password'))
        obj.password = ApiClient.convertToType(data['password'], ['String']);
    }
    return obj;
  }
}

/**
 * @member {String} nameOrEmail
 */
AccountLoginDto.prototype.nameOrEmail = undefined;

/**
 * @member {Array.<String>} password
 */
AccountLoginDto.prototype.password = undefined;

