/*
 * MoiKiitos API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.52
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The AccountRegistrationDto model module.
 * @module model/AccountRegistrationDto
 * @version v1
 */
export class AccountRegistrationDto {
  /**
   * Constructs a new <code>AccountRegistrationDto</code>.
   * @alias module:model/AccountRegistrationDto
   * @class
   * @param name {String} 
   * @param email {String} 
   * @param password {Array.<String>} 
   */
  constructor(name, email, password) {
    this.name = name;
    this.email = email;
    this.password = password;
  }

  /**
   * Constructs a <code>AccountRegistrationDto</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/AccountRegistrationDto} obj Optional instance to populate.
   * @return {module:model/AccountRegistrationDto} The populated <code>AccountRegistrationDto</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new AccountRegistrationDto();
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('email'))
        obj.email = ApiClient.convertToType(data['email'], 'String');
      if (data.hasOwnProperty('password'))
        obj.password = ApiClient.convertToType(data['password'], ['String']);
    }
    return obj;
  }
}

/**
 * @member {String} name
 */
AccountRegistrationDto.prototype.name = undefined;

/**
 * @member {String} email
 */
AccountRegistrationDto.prototype.email = undefined;

/**
 * @member {Array.<String>} password
 */
AccountRegistrationDto.prototype.password = undefined;

