/*
 * MoiKiitos API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.52
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The FeedQueryDto model module.
 * @module model/FeedQueryDto
 * @version v1
 */
export class FeedQueryDto {
  /**
   * Constructs a new <code>FeedQueryDto</code>.
   * @alias module:model/FeedQueryDto
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>FeedQueryDto</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/FeedQueryDto} obj Optional instance to populate.
   * @return {module:model/FeedQueryDto} The populated <code>FeedQueryDto</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new FeedQueryDto();
      if (data.hasOwnProperty('skip'))
        obj.skip = ApiClient.convertToType(data['skip'], 'Number');
      if (data.hasOwnProperty('limit'))
        obj.limit = ApiClient.convertToType(data['limit'], 'Number');
      if (data.hasOwnProperty('userId'))
        obj.userId = ApiClient.convertToType(data['userId'], 'Number');
    }
    return obj;
  }
}

/**
 * @member {Number} skip
 */
FeedQueryDto.prototype.skip = undefined;

/**
 * @member {Number} limit
 */
FeedQueryDto.prototype.limit = undefined;

/**
 * @member {Number} userId
 */
FeedQueryDto.prototype.userId = undefined;

