/*
 * MoiKiitos API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.52
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {User} from './User';

/**
 * The PageResultUser model module.
 * @module model/PageResultUser
 * @version v1
 */
export class PageResultUser {
  /**
   * Constructs a new <code>PageResultUser</code>.
   * @alias module:model/PageResultUser
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>PageResultUser</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PageResultUser} obj Optional instance to populate.
   * @return {module:model/PageResultUser} The populated <code>PageResultUser</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new PageResultUser();
      if (data.hasOwnProperty('items'))
        obj.items = ApiClient.convertToType(data['items'], [User]);
      if (data.hasOwnProperty('total'))
        obj.total = ApiClient.convertToType(data['total'], 'Number');
    }
    return obj;
  }
}

/**
 * @member {Array.<module:model/User>} items
 */
PageResultUser.prototype.items = undefined;

/**
 * @member {Number} total
 */
PageResultUser.prototype.total = undefined;

