/*
 * MoiKiitos API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.52
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {User} from './User';

/**
 * The Post model module.
 * @module model/Post
 * @version v1
 */
export class Post {
  /**
   * Constructs a new <code>Post</code>.
   * @alias module:model/Post
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>Post</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Post} obj Optional instance to populate.
   * @return {module:model/Post} The populated <code>Post</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Post();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('user'))
        obj.user = User.constructFromObject(data['user']);
      if (data.hasOwnProperty('content'))
        obj.content = ApiClient.convertToType(data['content'], 'String');
      if (data.hasOwnProperty('createAt'))
        obj.createAt = ApiClient.convertToType(data['createAt'], 'Date');
    }
    return obj;
  }
}

/**
 * @member {Number} id
 */
Post.prototype.id = undefined;

/**
 * @member {module:model/User} user
 */
Post.prototype.user = undefined;

/**
 * @member {String} content
 */
Post.prototype.content = undefined;

/**
 * @member {Date} createAt
 */
Post.prototype.createAt = undefined;

