/*
 * MoiKiitos API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.52
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The PostCreateDto model module.
 * @module model/PostCreateDto
 * @version v1
 */
export class PostCreateDto {
  /**
   * Constructs a new <code>PostCreateDto</code>.
   * @alias module:model/PostCreateDto
   * @class
   * @param content {String} 
   */
  constructor(content) {
    this.content = content;
  }

  /**
   * Constructs a <code>PostCreateDto</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PostCreateDto} obj Optional instance to populate.
   * @return {module:model/PostCreateDto} The populated <code>PostCreateDto</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new PostCreateDto();
      if (data.hasOwnProperty('content'))
        obj.content = ApiClient.convertToType(data['content'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} content
 */
PostCreateDto.prototype.content = undefined;

