/*
 * MoiKiitos API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.52
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The ResponseBodyEmitter model module.
 * @module model/ResponseBodyEmitter
 * @version v1
 */
export class ResponseBodyEmitter {
  /**
   * Constructs a new <code>ResponseBodyEmitter</code>.
   * @alias module:model/ResponseBodyEmitter
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>ResponseBodyEmitter</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ResponseBodyEmitter} obj Optional instance to populate.
   * @return {module:model/ResponseBodyEmitter} The populated <code>ResponseBodyEmitter</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ResponseBodyEmitter();
      if (data.hasOwnProperty('timeout'))
        obj.timeout = ApiClient.convertToType(data['timeout'], 'Number');
    }
    return obj;
  }
}

/**
 * @member {Number} timeout
 */
ResponseBodyEmitter.prototype.timeout = undefined;

